### PR TITLE
update to v10, fix default network

### LINKED ISSUE #273: Mainnet not used if token is omitted
Node should default to mainnet if no token is provided. Now error is thrown -

```
│ Activation account missing:                                                                                                                                                       │
│     failed to find one                                                                                                                                                            │
│ Importing keys                                                                                                                                                                    │
│   Writing /var/tezos/client/secret_keys                                                                                                                                           │
│   Writing /var/tezos/client/public_keys                                                                                                                                           │
│   Writing /var/tezos/client/public_key_hashs                                                                                                                                      │
│ Starting config.json file generation                                                                                                                                              │
│ Traceback (most recent call last):                                                                                                                                                │
│   File "/config-generator.py", line 569, in <module>                                                                                                                              │
│     main()                                                                                                                                                                        │
│   File "/config-generator.py", line 130, in main                                                                                                                                  │
│     create_node_config_json(                                                                                                                                                      │
│   File "/config-generator.py", line 550, in create_node_config_json                                                                                                               │
│     node_config["network"] = json.load(f)["network"]                                                                                                                              │
│ KeyError: 'network'
```

### PR DESCRIPTION
**Pull request by orcutt989**
Updates tezos to v10-release

Fixes issue when no creds are given.

Newlines appended to config-init.sh to prevent log from cutting off in k9s.

Fixes #273 #272

### CODE REVIEW

File: charts/tezos/scripts/config-init.sh [hunk 1]
```diff
@@ -10,3 +10,5 @@ mkdir -p /etc/tezos/data
     --network $CHAIN_NAME
 
 cat /etc/tezos/data/config.json
+
+printf "\n\n\n\n\n\n\n"
```
Comment (harryttd) [inline charts/tezos/scripts/config-init.sh:14]: Is this actually needed after our debugging?

Comment (nicolasochem) [reply charts/tezos/scripts/config-init.sh:14]: Yes, otherwise the last line of config is not printed in k9s. It's useful to me.

**Review by harryttd — APPROVED** [review]

**Review by elric1 — APPROVED** [review]
Looks good to me.

**Review by nicolasochem — APPROVED** [review]
